### PR TITLE
Fix BytesN parsing when using valid hex values.

### LINKED ISSUE #2245: contract invoke BytesN parsing fails to parse valid hex values
> why `"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"` succeed while `"4142434400000000000000000000000000000000000000000000000000000000"` fails? Both are properly formatted 64-chars hex strings representing 32 bytes. 

 _Originally posted by @jsmaxi in [#2239](https://github.com/stellar/stellar-cli/issues/2239#issuecomment-3380828974)_

### PR DESCRIPTION
**Pull request by fnando**
### What

Properly parse BytesN when using valid hex values.

### Why

Fix #2245.

### Known limitations

N/A

### CODE REVIEW

File: cmd/crates/soroban-spec-tools/src/lib.rs [hunk 1]
```diff
@@ -288,6 +288,9 @@ impl Spec {
                     ScType::U128 | ScType::I128 | ScType::U256 | ScType::I256 => {
                         Ok(Value::String(s.to_owned()))
                     }
+                    ScType::Bytes | ScType::BytesN(_) if matches!(val, Value::Number(_)) => {
+                        Ok(Value::String(s.to_owned()))
+                    }
```
Comment (leighmcculloch) [inline cmd/crates/soroban-spec-tools/src/lib.rs:293]: Adding this means that the existing `(ScType::BytesN(_), Value::Number(n))` and `(ScType::Bytes, Value::Number(n))` arms in `from_json_primitives` (lines 86-88, 104-106) are unreachable for inputs that flowing through `from_string` -> `from_json` -> `from_json_primitives`. This new code converts numbers to strings earlier. They're still reachable if someone calls `from_json` directly with a pre-built `Value::Number`.

**Review by leighmcculloch — APPROVED** [review]
Looks good, one comment inline because this shadows a code path that becomes dead and wondering if there's an error relating to that.

File: cmd/crates/soroban-spec-tools/src/lib.rs (hunk 1 above)
Comment (fnando) [reply cmd/crates/soroban-spec-tools/src/lib.rs:293]: Good call. I've replaced both `Value::Number` arms with explicit `InvalidValue` errors instead of the `format!("{n}")` conversion. Hex data in `Bytes`/`BytesN` should always be passed as quoted strings (e.g., `["4554"]` not `[4554]`), which avoids the `f64` precision loss entirely. Added tests covering both the direct `from_json_primitives` path and the nested `Vec<Bytes>` path.

Does that make sense?

Comment (leighmcculloch) [reply cmd/crates/soroban-spec-tools/src/lib.rs:293]: Won't quotes often be lost to shell expansion?

Comment (leighmcculloch) [reply cmd/crates/soroban-spec-tools/src/lib.rs:293]: Oh you're meaning specifically in JSON, yes that makes sense.
