### PR TITLE
Return error when fetching ledger entry for trustline using native asset.

### LINKED ISSUE #2394: `stellar ledger entry fetch trustline --asset xlm` shouldn't be supported
### What problem does your feature solve?

The `stellar ledger entry fetch trustline --asset` flag accepts `"XLM"` (mapped to `TrustLineAsset::Native`), but trustlines do not hold the native asset — the native balance is held on the account entry itself. Passing `--asset xlm` silently returns an empty result instead of telling the user the input is invalid:

```
$ stellar ledger entry fetch trustline --asset xlm --account GB6RQWLXTCVLJZX6LACXVD4WFZHX4YGIPPBSH2YQQMZIMEKA4BM7QLOU
{"entries":[],"latestLedger":61271020}
```

https://github.com/stellar/stellar-cli/blob/a1c94559a7fb05b58b4697d82e918be44eab4df5/cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs#L60-L61

### What would you like to see?

Return an error when `"XLM"` or `"native"` is passed as an `--asset` value, since trustlines cannot hold the native asset. For example:

```
error: native asset (XLM) does not have a trustline, use `stellar ledger entry fetch account` instead
```

### What alternatives are there?

Leave the behavior as-is, silently returning an empty result.

### PR DESCRIPTION
**Pull request by fnando**
### What

Return error when fetching ledger entry for trustline using native asset.

### Why

So it behaves like it should with native asset. Close #2394.

### Known limitations

N/A

### CODE REVIEW

File: cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs [hunk 1]
```diff
@@ -43,6 +43,8 @@ pub enum Error {
     Locator(#[from] locator::Error),
     #[error(transparent)]
     TryFromSliceError(#[from] TryFromSliceError),
+    #[error("native asset (XLM) does not have a trustline, use `stellar ledger entry fetch account` instead")]
```
Comment (leighmcculloch) [inline cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs]: Nice error text.

File: cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs [hunk 2]
```diff
@@ -57,8 +59,9 @@ impl Cmd {
     fn insert_asset_keys(&self, ledger_keys: &mut Vec<LedgerKey>) -> Result<(), Error> {
         let acc = self.muxed_account(&self.account)?;
         for asset in &self.asset {
-            let asset = if asset.eq_ignore_ascii_case("XLM") {
-                TrustLineAsset::Native
+            let asset = if asset.eq_ignore_ascii_case("XLM") || asset.eq_ignore_ascii_case("native")
```
Comment (leighmcculloch) [inline cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs]: I think we should remove this check. It's valid for someone to name an asset code xlm or native. We just need to require asset code and issuer to limit the lookup to issued assets that have an issuer.

File: cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs [hunk 3]
```diff
@@ -54,9 +54,7 @@ impl Cmd {
     fn insert_asset_keys(&self, ledger_keys: &mut Vec<LedgerKey>) -> Result<(), Error> {
         let acc = self.muxed_account(&self.account)?;
         for asset in &self.asset {
-            let asset = if asset.eq_ignore_ascii_case("XLM") {
-                TrustLineAsset::Native
```
Comment (mootz12) [inline cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs:58]: [picky] Can we will still error here with the helpful "native assets don't have trustlines" error message you had before if they provide `XLM` `xlm` or `native` exactly?

Comment (leighmcculloch) [reply cmd/soroban-cli/src/commands/ledger/entry/fetch/trustline.rs:58]: If we do, without the issuer, because XLM, xlm, native, are valid codes to use with an issuer.
