### PR TITLE
Fix/fee table for fee bump tx

### LINKED ISSUE #2101: `tx fetch fee` miscalculating resource fees for fee bump txns that wrap soroban txns
### What version are you using?
Using the cli built from `main`

### What did you do?

```
❯ cargo run tx fetch fee --hash 9422e024c72184f61694bd1c043f51435ff1bba292be2cc729c5bc70b8a9fde8 --network main
```

### What did you see?
```
┌────────────────────────────────────────────────────────────────────────────────────────────┐
│ Fee Proposed: 10208876                                                                     │
├────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 10208876 │ Resource Fee: 0                                                  │
├────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 10208876 │ Non-Refundable: 285226 │ Refundable: -285226                     │
│                         │                        │                                         │
│                         │ cpu instructions       │ return value                            │
│                         │ storage read/write     │ storage rent                            │
│                         │ tx size                │ events                                  │
├────────────────────────────────────────────────────────────────────────────────────────────┤
│                               👆 Proposed Fee  👇 Final Fee                                │
├────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 200      │ Non-Refundable: 285226 │ Refundable: 3317604 │ Refunded: 6605846 │
├────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 200      │ Resource Fee: 3602830                        │ Refunded: 6605846 │
├────────────────────────────────────────────────────────────────────────────────────────────┤
│ Fee Charged: 3603030                                                   │ Refunded: 6605846 │
└────────────────────────────────────────────────────────────────────────────────────────────┘
```

### What did you expect to see?
the refundable fee should not be negative

Shout out to @quietbits for finding this bug!

### PR DESCRIPTION
**Pull request by elizabethengelman**
### What

Closes #2101 

### Why

We were previously miscalculating the resource fees for fee bump transactions that wrap soroban transactions. This PR fixes that by looking at the inner transaction to get the proposed resource fee.

This PR also includes some refactoring to make the fee calculation easier to understand & test.

Before:
```
❯ stellar tx fetch fee --hash e7a6268b66d6fe2c8a89941062c4012d4b020b91c2d98cd18d98b3b34ed296d4 --network main
┌──────────────────────────────────────────────────────────────────────────────────────┐
│ Fee Proposed: 255364                                                                 │
├──────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 255364 │ Resource Fee: 0                                              │
├──────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 255364 │ Non-Refundable: 165209 │ Refundable: -165209                 │
│                       │                        │                                     │
│                       │ cpu instructions       │ return value                        │
│                       │ storage read/write     │ storage rent                        │
│                       │ tx size                │ events                              │
├──────────────────────────────────────────────────────────────────────────────────────┤
│                            👆 Proposed Fee  👇 Final Fee                             │
├──────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 200    │ Non-Refundable: 165209 │ Refundable: 23118 │ Refunded: 66837 │
├──────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 200    │ Resource Fee: 188327                       │ Refunded: 66837 │
├──────────────────────────────────────────────────────────────────────────────────────┤
│ Fee Charged: 188527                                                │ Refunded: 66837 │
└──────────────────────────────────────────────────────────────────────────────────────┘
```

After:
```
❯ cargo run tx fetch fee --hash e7a6268b66d6fe2c8a89941062c4012d4b020b91c2d98cd18d98b3b34ed296d4 --network main
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Fee Proposed: 255364                                                                                      │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 201         │ Resource Fee: 255163                                                         │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 201         │ Non-Refundable: 165209         │ Refundable: 89954                           │
│                            │                                │                                             │
│                            │ cpu instructions               │ return value                                │
│                            │ storage read/write             │ storage rent                                │
│                            │ tx size                        │ events                                      │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                       👆 Proposed Fee  👇 Final Fee                                       │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 200 │ Non-Refundable Charged: 165209 │ Refundable Charged: 23118 │ Refunded: 66837 │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 200 │ Resource Fee Charged: 188327                               │ Refunded: 66837 │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Fee Charged: 188527                                                                     │ Refunded: 66837 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

### Known limitations

n/a

### CODE REVIEW

File: cmd/soroban-cli/src/commands/tx/fetch/fee.rs [hunk 1]
```diff
@@ -86,104 +97,152 @@ impl Cmd {
...
-
-                (fee.into(), resource_fee)
+                ProposedFees {
+                    fee,
+                    resource_fee,
+                    inclusion_fee: fee - resource_fee,
+                }
             }
             TransactionEnvelope::TxFeeBump(fee_bump_transaction_envelope) => {
+                let inner_tx_resource_fee = match &fee_bump_transaction_envelope.tx.inner_tx {
```
Comment (elizabethengelman) [inline cmd/soroban-cli/src/commands/tx/fetch/fee.rs:173]: This is the main fix in this PR - instead of assuming all fee bump transactions have a resource fee of 0, like were we previously doing, we're now digging into the inner tx to see if its a soroban tx. If it is a classic tx, we can return the default resource fee, 0. If it's a soroban tx, we can return the inner tx's resource fee.

**Review by leighmcculloch — APPROVED** [review]
