### PR TITLE
Handle contract build info when multiple attestations are available.

### LINKED ISSUE #2358: `stellar contract info build` fails when multiple attestations exist (release + SLSA)
### What version are you using?

`23.4.1`

### What did you do?

```
stellar contract info build --contract-id CDV6FVU76E2UPXMXLZEBIF2PSKVXC7GGTNE6CBWNATTBYMID2FQPNO56
```

### What did you expect to see?

The command should return build provenance info from the SLSA attestation (the GitHub Actions run details) without error.

### What did you see instead?

```
stellar contract info build --contract-id CDV6FVU76E2UPXMXLZEBIF2PSKVXC7GGTNE6CBWNATTBYMID2FQPNO56

⚠️ This command displays information about the GitHub Actions run that attested to have built the wasm, and does not verify the source code. Please review the run, its workflow, and source code.
ℹ️ Network: Test SDF Network ; September 2015
🌎 Downloading contract spec: CDV6FVU76E2UPXMXLZEBIF2PSKVXC7GGTNE6CBWNATTBYMID2FQPNO56
ℹ️ Wasm Hash: 3c8d0b8b347752e57abe0b50380401ca8f5793bc971b685fd072571bbf5d54cc
ℹ️ Source Repo: github:stellar/sep45-reference
ℹ️ Collecting GitHub attestation from https://api.github.com/repos/stellar/sep45-reference/attestations/sha256:3c8d0b8b347752e57abe0b50380401ca8f5793bc971b685fd072571bbf5d54cc
❌ error: missing field `buildDefinition` at line 1 column 568
```

### Additional context

There are multiple attestations for this Wasm because GitHub attached a `Release attestation` to the release, and the command expects the provenance attestation first. I suspect this was added because the release is immutable.

```curl -s -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/stellar/sep45-reference/attestations/sha256:3c8d0b8b347752e57abe0b50380401ca8f5793bc971b685fd072571bbf5d54cc" |
jq '{count: (.attestations | length), predicate_types: [.attestations[].bundle.dsseEnvelope.payload | @base64d | fromjson | .predicateType]}'

{
  "count": 2,
  "predicate_types": [
    "https://in-toto.io/attestation/release/v0.2",
    "https://slsa.dev/provenance/v1"
  ]
}
````

### PR DESCRIPTION
**Pull request by fnando**
### What

Handle contract build info when multiple attestations are available.

```console
$ stellar contract info build --contract-id CDV6FVU76E2UPXMXLZEBIF2PSKVXC7GGTNE6CBWNATTBYMID2FQPNO56
⚠️ This command displays information about the GitHub Actions run that attested to have built the wasm, and does not verify the source code. Please review the run, its workflow, and source code.
ℹ️ Network: Test SDF Network ; September 2015
🌎 Downloading contract spec: CDV6FVU76E2UPXMXLZEBIF2PSKVXC7GGTNE6CBWNATTBYMID2FQPNO56
ℹ️ Wasm Hash: 3c8d0b8b347752e57abe0b50380401ca8f5793bc971b685fd072571bbf5d54cc
ℹ️ Source Repo: github:stellar/sep45-reference
ℹ️ Collecting GitHub attestation from https://api.github.com/repos/stellar/sep45-reference/attestations/sha256:3c8d0b8b347752e57abe0b50380401ca8f5793bc971b685fd072571bbf5d54cc
✅ Attestation found linked to GitHub Actions Workflow Run:
    Repository: https://github.com/stellar/sep45-reference
    Ref:        refs/tags/v0.1.3
    Path:       .github/workflows/release.yml
    Git Commit: 3dcabc965f01512a631d2c0c6999786f5f6a01cd
    Runner:     github-hosted
    Run:        https://github.com/stellar/sep45-reference/actions/runs/21009985939/attempts/1
🌎 View the workflow at https://github.com/stellar/sep45-reference/blob/3dcabc965f01512a631d2c0c6999786f5f6a01cd/.github/workflows/release.yml
🌎 View the repo at https://github.com/stellar/sep45-reference/tree/3dcabc965f01512a631d2c0c6999786f5f6a01cd
```

### Why

Close #2358

### Known limitations

N/A

### CODE REVIEW

File: cmd/soroban-cli/src/commands/contract/info/build.rs [hunk 1]
```diff
@@ -84,16 +84,28 @@ impl Cmd {
...
-        let payload: gh_payload::Root = serde_json::from_slice(&payload)?;
+
+        // Find the SLSA provenance attestation (not the Release attestation)
+        // GitHub may attach multiple attestations, and we need the one with predicate_type
+        // matching "https://slsa.dev/provenance/v1"
+        let payload = resp
+            .attestations
+            .iter()
+            .find_map(|attestation| {
+                let payload = base64::engine::general_purpose::STANDARD
```
[the remark this answers is not in the document]
Comment (fnando) [reply cmd/soroban-cli/src/commands/contract/info/build.rs:95]: no

File: cmd/soroban-cli/src/commands/contract/info/build.rs [hunk 2]
```diff
@@ -84,16 +84,25 @@ impl Cmd {
...
-            return Err(Error::AttestationNotFound);
-        };
-        let Ok(payload) = base64::engine::general_purpose::STANDARD
-            .decode(&attestation.bundle.dsse_envelope.payload)
-        else {
-            return Err(Error::AttestationInvalid);
-        };
-        let payload: gh_payload::Root = serde_json::from_slice(&payload)?;
+
+        // Find the SLSA provenance attestation (not the Release attestation)
```
Comment (leighmcculloch) [inline cmd/soroban-cli/src/commands/contract/info/build.rs:88]: What is a Release attestation?

Comment (fnando) [reply cmd/soroban-cli/src/commands/contract/info/build.rs:88]: looks like it's a new thing: https://docs.github.com/en/code-security/concepts/supply-chain-security/immutable-releases
