### PR TITLE
Fix muxed parsing issue

### LINKED ISSUE #2125: Can invoke contract passing muxed address as an argument
### What version are you using?

```console
$ stellar doctor
✅ You are using the latest version of Stellar CLI: 23.0.1
ℹ️ Rust version: 1.89.0
✅ Rust target `wasm32v1-none` is installed
⚙️ Config directory: /Users/fnando/.config/stellar
ℹ️ XDR version: 4b7a2ef7931ab2ca2499be68d849f38190b443ca
🌎 Default network "local" (http://localhost:8000/rpc)
   protocol 23
   rpc 23.0.0-rc.2
🌎 Default network "futurenet" (https://rpc-futurenet.stellar.org:443)
   protocol 23
   rpc 23.0.0~rc3-33982801b3d320ef9aac958dff97348159b0e989
🌎 Default network "testnet" (https://soroban-testnet.stellar.org)
   protocol 23
   rpc 23.0.0~rc2-f384ceb94914d80eed0f59524de7096c726b9054
🌎 Network "mainnet" (https://mainnet.sorobanrpc.com)
   protocol 22
   rpc 22.1.5-d3fceb70d3b1fd585a5076aef1beabc408aa6142
```

### What did you do?

```console
$ stellar network use futurenet
$ stellar contract invoke --id CB64D3G7SM2RTH6JSGG34DDTFTQ5CFDKVDZJZSODMCX4NJ2HV2KN7OHT -- balance --id MA5XIGA5C7QTPTWXQHY6MCJRMTRZDOSHR6EFIBNDQTCQHG262N4GGGC2XZXD7G7EWH7U6
❌ error: parsing argument id: value is not parseable to Some(
    Address,
)
```

### What did you expect to see?

The contract to be invoked.

### What did you see instead?

An error.

### PR DESCRIPTION
**Pull request by sisuresh**
### What

Resolves #2125 

This will allow the CLI to take a muxed address as input.

### CODE REVIEW

File: cmd/crates/soroban-spec-tools/src/lib.rs [hunk 1]
```diff
@@ -1475,6 +1488,17 @@ mod tests {
             ),
             Err(e) => panic!("Unexpected error: {e}"),
         }
+
+        // MuxedAddress test
+        match sc_address_from_json(
```
Comment (leighmcculloch) [inline cmd/crates/soroban-spec-tools/src/lib.rs:1493]: Can you add a test for going in the reverse direction?

Comment (sisuresh) [reply cmd/crates/soroban-spec-tools/src/lib.rs:1493]: Done
