### PR TITLE
Fix/rpc header

### LINKED ISSUE #1728: Unable to connect to RPC Endpoint that requires API key
I am able to add an RPC Header while using the rc version of the cli but it doesn't seem like it is actually using the header. I get 403 errors when trying to connect to an RPC that requires an API key.

### What version are you using?

stellar 22.0.0-rc.1 (715a2008090afdc6c538a1c373d89709981181d6)
stellar-xdr 22.0.0-rc.1.1 (72e523004b5906eb1829990f9b14d2f0fa3018f0)
xdr curr (529d5176f24c73eeccfa5eba481d4e89c19b1181)

### What did you do?

Add an RPC URL and RPC Header

`stellar network add --rpc-url 'https://rpc-testnet.nodeswithobsrvr.co'  --network-passphrase 'Test SDF Network ; September 2015' --rpc-header 'Authorization: Api-Key 4mDhDFDFDGHhhhhhrtttttttt'  obsrvr-testnet`

And then attempted to invoke a contract

`stellar contract invoke --id CBO476K55KTBBS4HJB2VFVKZA6SR52RH2VRWHBPG4TZTR3OXKRELBBFW  --source stellartestnet2 --network obsrvr-testnet --very-verbose -- provision_environment --user alice2  --env_type hz25 --resources 8 --duration 10`

### What did you expect to see?

```
stellar contract invoke --id CBO476K55KTBBS4HJB2VFVKZA6SR52RH2VRWHBPG4TZTR3OXKRELBBFW  --source stellartestnet2 --network testnet -- provision_environment --user alice2  --env_type hz25 --resources 8 --duration 10
ℹ️ Signing transaction: 926a84a6ffda76fe46d84b387a4b46b8697c95df79081a5de7384bdddc529d56
2024-11-14T17:29:01.582055Z  INFO contract_event: soroban_cli::log::event: 1: AAAAAQAAAAAAAAABXc/5XeqmEMuHSHVS1VkHpR7qJ9VjY4Xm5PM47ddUSLAAAAABAAAAAAAAAAIAAAAPAAAACXByb3Zpc2lvbgAAAAAAAA0AAAAgRoa3LDbAcNcnZoQyHIZtjBQLFDFHJPSpDcVZxlAGnRgAAAARAAAAAQAAAAMAAAAPAAAACGVudl90eXBlAAAADwAAAARoejI1AAAADwAAAApleHBpcmF0aW9uAAAAAAAFAAAAAGc2M2gAAAAPAAAACXJlc291cmNlcwAAAAAAAAMAAAAI {"in_successful_contract_call":true,"event":{"ext":"v0","contract_id":"5dcff95deaa610cb87487552d55907a51eea27d5636385e6e4f338edd75448b0","type_":"contract","body":{"v0":{"topics":[{"symbol":"provision"},{"bytes":"4686b72c36c070d7276684321c866d8c140b14314724f4a90dc559c650069d18"}],"data":{"map":[{"key":{"symbol":"env_type"},"val":{"symbol":"hz25"}},{"key":{"symbol":"expiration"},"val":{"u64":1731605352}},{"key":{"symbol":"resources"},"val":{"u32":8}}]}}}}}
"4686b72c36c070d7276684321c866d8c140b14314724f4a90dc559c650069d18"
```

### What did you see instead?

I received a 403 error

```
2024-11-14T17:24:42.232241Z DEBUG soroban_cli::upgrade_check: start upgrade check
2024-11-14T17:24:42.232345Z TRACE soroban_cli::commands::contract::invoke: network=Network { rpc_url: "https://rpc-testnet.nodeswithobsrvr.co", rpc_headers: [("Authorization", "Api-Key 4mDhDFDFDGHhhhhhrtttttttt")], network_passphrase: "Test SDF Network ; September 2015" }
2024-11-14T17:24:42.232371Z DEBUG soroban_cli::upgrade_check: finished upgrade check
2024-11-14T17:24:43.898052Z TRACE soroban_cli::get_spec: network=Network { rpc_url: "https://rpc-testnet.nodeswithobsrvr.co", rpc_headers: [("Authorization", "Api-Key 4mDhDFDFDGHhhhhhrtttttttt")], network_passphrase: "Test SDF Network ; September 2015" }
❌ error: Networking or low-level protocol error: Server returned an error status code: 403
```

Using httpie works fine
```
http POST https://rpc-testnet.nodeswithobsrvr.co 'Authorization: Api-Key 4mDhDFDFDGHhhhhhrtttttttt' jsonrpc="2.0" id:=1 method="getLatestLedger"
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "id": "fbacaeb65d94773da05213375c83c82caeabfac14463e864acc86c9e9e0ef3ec",
        "protocolVersion": 22,
        "sequence": 955485
    }
}
```

### PR DESCRIPTION
**Pull request by elizabethengelman**
### What
This PR makes sure to use the `Network.rpc_client` function when getting an rpc client, instead of creating one with `Client::new.  It's important to do use `rpc_client` because it makes sure to pass in additional headers to the rpc client, including adding auth headers which are needed for some rpc providers. 

This change was made in:
- `Network.helper_url`
- `get_remote_contract_spec`: This was the main reason for the bug reported in #1728, because `invoke` calls `get_remote_contract_spec`.
- several integration tests

Fixes #1728. 

### Why

As part of supporting third-party rpc providers, we need to pass in the authentication as a header for some providers. This was done in #1618 , but must have missed making the update to other scenarios that were creating a new rpc client with `Client::new`.

### Known limitations

Curious to hear what others think, but as the rpc client is currently written, it is still possible to create an rpc client with required headers using `Client::new`. While having the flexibility is nice, does it make sense to deprecate this function and rely on `new_with_headers` instead? This would be a change made to the rpc client repo.

### CODE REVIEW

**Review by willemneal — APPROVED** [review]
Looks good to me!

File: cmd/crates/soroban-test/tests/it/rpc_provider.rs [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+    let generate_account_mock = mock_generate_account(&server);
+    let get_network_mock = mock_get_network(&server);
+    let get_events_mock = mock_get_events(&server);
+
+    // create a new test environment with the mock server
+    let rpc_url = server.url("");
+    let rpc_headers = vec![("Authorization".to_string(), "Bearer test-token".to_string())];
+    let sandbox = &TestEnv::with_rpc_provider(&rpc_url, rpc_headers);
+
+    sandbox
```
Comment (Ifropc) [inline cmd/crates/soroban-test/tests/it/rpc_provider.rs:19]: Should we check that the response contains expected JSON?

**Comment by leighmcculloch** [comment]
> While having the flexibility is nice, does it make sense to deprecate this function and rely on `new_with_headers` instead? This would be a change made to the rpc client repo.

👍🏻. It's breaking so we'd need to delay the actual removal until the next major release, but you could add a deprecated attribute now.

**Review by leighmcculloch — APPROVED** [review]

File: cmd/crates/soroban-test/tests/it/rpc_provider.rs (hunk 1 above)
Comment (leighmcculloch) [reply cmd/crates/soroban-test/tests/it/rpc_provider.rs:19]: It's a mock so not sure that would be of benefit?

**Comment by leighmcculloch** [comment]
@elizabethengelman Can you fix the cargo-deny bans issues, try to align on not duplicate deps or if it's not possible, then add a line in the deny toml to allow the dupe deps?

**Comment by leighmcculloch** [comment]
This PR is blocked on a legal sign off because the http-mock uses a license we don't currently have approved. I expect it'll just be a formality in this case.

**Comment by leighmcculloch** [comment]
> This PR is blocked on a legal sign off because the http-mock uses a license we don't currently have approved. I expect it'll just be a formality in this case.

Unblocked and I pushed a modification to deny.toml for the license approval.

**Review by leighmcculloch — APPROVED** [review]
I think this is good to go, except for the bans need updating.

**Review by leighmcculloch — APPROVED** [review]
I think this is good to go, except for the bans need updating.

File: cmd/crates/soroban-test/tests/it/rpc_provider.rs (hunk 1 above)
Comment (elizabethengelman) [reply cmd/crates/soroban-test/tests/it/rpc_provider.rs:19]: Good question - since this test is mocking out the request to the rpc provider, I think it's okay not to check that response since it will be the `GetEventsResponse` that we're telling the provider to return on line 91. But I'm happy to rethink that!

**Comment by elizabethengelman** [comment]
@leighmcculloch cargo-deny bans have been fixed - was able to move `httpmock` to dev-dependencies to fix this, which it probably should have been anyways.
