### PR TITLE
Issues/2294 invalid hash arg parsing

### LINKED ISSUE #2294: Invalid argument parsing for byte strings
### What version are you using?

```
% stellar --version
stellar 23.2.0 (8c559e832fd969aa469784b66e70891fadf94f0a)
stellar-xdr 23.0.0 (e83a6337204ecfdb0ac0d44ffb857130c1249b1b)
xdr curr (4b7a2ef7931ab2ca2499be68d849f38190b443ca)
```

### What did you do?

```
% stellar contract invoke --id test_contract --source test -- upgrade --new_wasm_hash 3e981b3b5170e8e08429813b01b4aae93effef93e9fc4b8d62ecd205279c23ee
❌ error: Invalid JSON in argument 'new_wasm_hash': number out of range at line 1 column 5

Received value: '3e981b3b5170e8e08429813b01b4aae93effef93e9fc4b8d62ecd205279c23ee'

Suggestions:
- Check for missing quotes around strings
- Ensure proper JSON syntax (commas, brackets, etc.)
- For complex objects, consider using --new_wasm_hash-file-path to load from a file
```

### What did you expect to see?

The transaction to be successful

### What did you see instead?

Errored on transaction creation

### PR DESCRIPTION
**Pull request by mootz12**
### What

Adds missing primitive types to skip json validation, and patches timepoint and duration parsing

### Why

Fixes #2294 

### Known limitations

None

### CODE REVIEW

File: cmd/crates/soroban-test/tests/it/arg_parsing.rs [hunk 1]
```diff
@@ -130,29 +148,34 @@ fn parse_bytesn_when_hex_is_all_numbers() {
...
-    // println!("{res}");
-    println!(
-        "{:#?}",
-        from_string_primitive("hello", &ScSpecTypeDef::Symbol).unwrap()
-    );
+    let parsed = from_string_primitive("hello", &ScSpecTypeDef::Symbol).unwrap();
+    assert!(parsed == ScVal::Symbol("hello".try_into().unwrap()));
 }
 
 #[test]
```
Comment (mootz12) [inline cmd/crates/soroban-test/tests/it/arg_parsing.rs:185]: Skipped adding validation here as it was taking too long to get correct and given this was an active bug, will follow up later
