### PR TITLE
Make `--cost` functional.

### LINKED ISSUE #2255: `stellar contract invoke --cost` is not working
### What did you do?

```console
$ stellar contract invoke --cost --send=yes --id hello -- hello --to 'fnando'
ℹ️ Signing transaction: da92da9ab506d9725380b57fe40b9aacdd05cd62cca005b28ff1a05e15c04291
["Hello","fnando"]
```

### What did you expect to see?

The cost, as advertised by the help.

```console
$ stellar contract invoke --help | grep cost
      --cost
          Output the cost execution to stderr
```

### What did you see instead?

No cost output.

### PR DESCRIPTION
**Pull request by fnando**
### What

```console
$ stellar contract extend --id hello --ledgers-to-extend 100000 --cost
ℹ️ Signing transaction: 1e6875d5e9c858215818466d50e98ed21adb3d82f97ca0846856954f2a50e7cd
┌─────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Fee Proposed: 46924                                                                                 │
├─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 100         │ Resource Fee: 46824                                                    │
├─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 100         │ Non-Refundable: 8106         │ Refundable: 38718                       │
│                            │                              │                                         │
│                            │ cpu instructions             │ return value                            │
│                            │ storage read/write           │ storage rent                            │
│                            │ tx size                      │ events                                  │
├─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                    👆 Proposed Fee  👇 Final Fee                                    │
├─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 100 │ Non-Refundable Charged: 8106 │ Refundable Charged: 0 │ Refunded: 38718 │
├─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 100 │ Resource Fee Charged: 8106                           │ Refunded: 38718 │
├─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Fee Charged: 8206                                                                 │ Refunded: 38718 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────┘
ℹ️ No changes detected, transaction was a no-op.
New ttl ledger: 146298

$ stellar contract invoke --cost --send=yes --id hello -- hello --to 'fnando'
ℹ️ Signing transaction: 812e0c833e2a4ccfda2be3c0720b297340c5859bb66e259b96d3c4026bb841d1
┌────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Fee Proposed: 50906                                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 100         │ Resource Fee: 50806                                                       │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 100         │ Non-Refundable: 11594         │ Refundable: 39212                         │
│                            │                               │                                           │
│                            │ cpu instructions              │ return value                              │
│                            │ storage read/write            │ storage rent                              │
│                            │ tx size                       │ events                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                     👆 Proposed Fee  👇 Final Fee                                      │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 100 │ Non-Refundable Charged: 11594 │ Refundable Charged: 430 │ Refunded: 38782 │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 100 │ Resource Fee Charged: 12024                             │ Refunded: 38782 │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Fee Charged: 12124                                                                   │ Refunded: 38782 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────┘
["Hello","fnando"]
```

### Why

Close #2255.

### Known limitations

N/A

### CODE REVIEW

File: cmd/soroban-cli/src/fee.rs [hunk 1]
```diff
@@ -38,6 +39,27 @@ impl Args {
...
+        // Extract fee information from the transaction
+        if let xdr::TransactionExt::V1(xdr::SorobanTransactionData { resource_fee, .. }) = &txn.ext
+        {
+            let total_fee = i64::from(txn.fee);
+            let base_fee = total_fee - resource_fee;
+
+            print.infoln("Cost info:");
+            print.blankln(format!("Total Fee: {total_fee} stroops"));
+            print.blankln(format!("Resource Fee: {resource_fee} stroops"));
+            print.blankln(format!("Base Inclusion Fee: {base_fee} stroops"));
```
Comment (leighmcculloch) [inline cmd/soroban-cli/src/fee.rs]: We state that this is the cost info, but this is also just the predicted / simulated cost, not the actual cost for a submitted tx. For a submitted tx it would probably be more helpful to have the latter.

Also, I think we should consider whether this output should be the same as the output of `stellar tx fetch fee`. A simulated cost info would only show the proposed fee data, not the final fee. It's a lot of info to show, but even if we only show a subset, we should be consistent in language sot hat someone looking at the cost info printed in this change or via this other command, they should be able to marry them.

```
$ stellar tx fetch fee --hash b34fb795b9e4d906d42a9627281201dc317ea03c5dc23a361e5cf967872390d3
Transaction Status: SUCCESS
Transaction Ledger: 59383339
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Fee Proposed: 169324                                                                                      │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 200         │ Resource Fee: 169124                                                         │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 200         │ Non-Refundable: 102491         │ Refundable: 66633                           │
│                            │                                │                                             │
│                            │ cpu instructions               │ return value                                │
│                            │ storage read/write             │ storage rent                                │
│                            │ tx size                        │ events                                      │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                       👆 Proposed Fee  👇 Final Fee                                       │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 200 │ Non-Refundable Charged: 102491 │ Refundable Charged: 24517 │ Refunded: 42116 │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 200 │ Resource Fee Charged: 127008                               │ Refunded: 42116 │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Fee Charged: 127208                                                                     │ Refunded: 42116 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Comment (leighmcculloch) [reply cmd/soroban-cli/src/fee.rs]: > we should be consistent in language

I think this would mean "Total Fee" -> "Fee Proposed". "Base Inclusion Fee" -> "Inclusion Fee".

Comment (leighmcculloch) [reply cmd/soroban-cli/src/fee.rs]: Maybe we should change Fee Proposed in `stellar tx fetch fee` to `Total Fee (Proposed)`, and `Fee Charged` to `Total Fee (Charged)`. Because the "total" language you're using here in the cost info is better I think.

Comment (fnando) [reply cmd/soroban-cli/src/fee.rs]: So, do you think we should do it conditionally? If `--build-only` is provided, the simulated fees should be displayed. Otherwise, we can should the actual cost, because we'd have a transaction to display the fees.

Comment (fnando) [reply cmd/soroban-cli/src/fee.rs]: Does this look good?

```console
$ stellar contract invoke --cost --send=yes --id hello -- hello --to 'fnando'
ℹ️ Signing transaction: e76b1096a46c9a732f386cac14ba0860b9e13d9ff6172b4f79224157cf627eea
┌────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Fee Proposed: 50906                                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 100         │ Resource Fee: 50806                                                       │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee: 100         │ Non-Refundable: 11594         │ Refundable: 39212                         │
│                            │                               │                                           │
│                            │ cpu instructions              │ return value                              │
│                            │ storage read/write            │ storage rent                              │
│                            │ tx size                       │ events                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                     👆 Proposed Fee  👇 Final Fee                                      │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 100 │ Non-Refundable Charged: 11594 │ Refundable Charged: 430 │ Refunded: 38782 │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Inclusion Fee Charged: 100 │ Resource Fee Charged: 12024                             │ Refunded: 38782 │
├────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Fee Charged: 12124                                                                   │ Refunded: 38782 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────┘
["Hello","fnando"]
```

Comment (leighmcculloch) [reply cmd/soroban-cli/src/fee.rs]: Wow that is intense. But yeah, I think so. And for --send=no, just the first half, and for --build-only, we can't really emit anything until simulation.

Comment (leighmcculloch) [reply cmd/soroban-cli/src/fee.rs]: --build-only doesn't do simulation

Comment (leighmcculloch) [reply cmd/soroban-cli/src/fee.rs]: Maybe in the send case we should print the two parts separately. So print the first half during simulation, then second half after send.

Comment (fnando) [reply cmd/soroban-cli/src/fee.rs]: I'll tackle simulation cost in a separate pr, given that this is already better than before (at least it does _something_).
